name: "Prepare GitHub release"

on:
  push:

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: zip
        run: |
          sudo apt-get install make gettext
          make zip-file
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zip
          path: "*.zip"
      - name: Release (pre)
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          prerelease: true
        if: contains(github.ref_name,'rc') && github.ref_type == 'tag'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
        if: "!contains(github.ref_name,'rc') && github.ref_type == 'tag'"
